# Use a Python base image
FROM python:3.9-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the Python file into the container
COPY HelloWorld.py .

# Run HelloWorld.ipynb when the container launches
CMD ["python", "HelloWorld.py"]